[package]
name = "rs-shell"
version = "0.0.0"
edition = "2021"
description = "[PLACEHOLDER] a basic shell writen in rust"
licence = "none"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
